FROM openjdk:21-jdk

ARG PROFILE
ENV PROFILE ${PROFILE}

ARG MONGO_DB
ENV MONGO_DB ${MONGO_DB}

ARG MONGO_URI
ENV MONGO_URI ${MONGO_URI}

ARG DB_USERNAME
ENV DB_USERNAME ${DB_USERNAME}

ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}

ARG LOGIN_URL
ENV LOGIN_URL ${LOGIN_URL}

ARG REDIS_HOST
ENV REDIS_HOST ${REDIS_HOST}

ARG SECRET_KEY
ENV SECRET_KEY ${SECRET_KEY}

ARG JAR_FILE=./build/libs/*.jar
COPY ${JAR_FILE} application.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "application.jar"]

