spring:
  data:
    mongodb:
      database: ${MONGO_DB}
      uri: ${MONGO_URI}
      auto-index-creation: true
      password: ${DB_PASSWORD}
      username: ${DB_USERNAME}

  threads:
    virtual:
      enabled: true
jwt:
  header: Authorization
  prefix: Bearer
  secret: ${SECRET}
  accessExpiration: 271000
  refreshExpiration: 604800
redis:
  host: ${REDIS_HOST}
  port: 6379

key:
  login-api-url: ${LOGIN_URL}

generation:
  one: 2015