spring:
  data:
    mongodb:
      database: ${MONGO_DB}
      uri: ${MONGO_URI}
      auto-index-creation: true

  threads:
    virtual:
      enabled: true
jwt:
  header: Authorization
  prefix: Bearer
  secret: ${SECRET}
  accessExpiration: 271000
  refreshExpiration: 604800
redis:
  host: 127.0.0.1
  port: 6379

key:
  login-api-url: sadasdasd

generation:
  one: 2015

server:
  servlet:
    context-path: /whopper
  port: 8080