spring:
  data:
    mongodb:
      database: ${MONGO_DB}
      uri: ${MONGO_URI}
      auto-index-creation: true

  threads:
    virtual:
      enabled: true

redis:
  host: ${REDIS_HOST}
  port: 6379